# Generated by Django 5.0.2 on 2024-02-25 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='Mobile_No',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
