# Generated by Django 5.0.2 on 2024-02-25 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0002_alter_customer_info_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='Mobile_No',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
