# Generated by Django 5.0.2 on 2024-02-25 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0003_alter_customer_info_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='Invoice_no',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='Name',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters.', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
