# Generated by Django 5.0.2 on 2024-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_alter_customer_info_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='Invoice_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
