# Generated by Django 5.0.2 on 2024-03-03 07:31

import StoreApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0006_alter_customer_info_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='Invoice_no',
            field=models.CharField(max_length=70, unique=True, validators=[StoreApp.models.validate_positive, django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
