# Generated by Django 4.2.2 on 2024-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0008_draw_date_alter_customer_info_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='dr_date',
            field=models.DateField(default=None),
        ),
    ]
