# Generated by Django 5.0.1 on 2024-03-07 03:43

import StoreApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0009_customer_info_dr_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters.', regex='^[a-zA-Z\\s]*$')])),
                ('Mobile_No', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('Invoice_no', models.CharField(max_length=70, unique=True, validators=[StoreApp.models.validate_positive])),
                ('Invoice_date', models.DateField()),
                ('Amount', models.PositiveIntegerField()),
                ('Token_id', models.CharField(editable=False, unique=True)),
                ('dr_date', models.DateField(default=None)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('IP_Address', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='customer_info',
            name='time',
            field=models.TimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
