# Generated by Django 5.0.1 on 2024-03-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0010_deleted_records_customer_info_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_records',
            name='Token_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
