# Generated by Django 5.0.1 on 2024-03-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0011_alter_deleted_records_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_records',
            name='Token_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
