# Generated by Django 5.0.1 on 2024-03-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0012_alter_deleted_records_token_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deleted_records',
        ),
        migrations.AddField(
            model_name='customer_info',
            name='deleted_by_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer_info',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
